groups:
  - name: General
    always_on: true
    variables:
      - name: Run ID
        type: text
        default: ""
        required: true
      - name: Operator
        type: text
        default: ""
        required: true
      - name: Experiment type
        type: select
        options: [Setup, Weld, AM, Flat]
        default: Setup
        required: true
      - name: Notes
        type: text
        default: ""
        required: false

  - name: X-ray beam settings
    always_on: false
    variables:
      - name: Beamline
        type: select
        options: [DLS I12, ESRF ID19, HEPS ID23, APS ID32, Other]
        default: DLS I12
      - name: Beam Energy (KeV)
        type: float
        default: 0
      - name: Exposure time (us)
        type: float
        default: 0
      - name: Framerate (kfps)
        type: float
        default: 0
      - name: Pixel Size (um)
        type: float
        default: 0
      - name: X-ray scan number
        type: integer
        default: 0

  - name: Materials
    always_on: true
    variables:
      - name: Substrate ID
        type: text
        default: ""
      - name: Substrate material
        type: text
        default: ""
      - name: Powder material
        type: text
        default: ""

  - name: Laser Processing Parameters
    always_on: true
    variables:
      - name: Laser in use
        type: text
        default: "TruFiber 500 P compact (FD44-A) 1 PCE 500 W Fiber Laser"
      - name: Laser Power (W)
        type: float
        default: 0
      - name: Scan Speed (mm/s)
        type: float
        default: 0
      - name: Laser Spot Size (mm)
        type: float
        default: 0

  - name: Ultrasonic Processing Parameters
    always_on: false
    variables:
      - name: Amplitude (%)
        type: float
        default: 0
      - name: Frequency (kHz)
        type: float
        default: 35.14

  - name: Equipment in use
    always_on: true
    variables:
      - name: Laser
        type: text
        default: "TruFiber 500 P compact (FD44-A)"
      - name: Powder feeder
        type: text
        default: "GTV PF 2/2 LC"
      - name: Sample manipulation
        type: text
        default: "Meca500 6-axis Robotic arm"